### ISSUE TITLE
intervals for reporting exercise

### ISSUE THREAD

**Issue by jennifershivers** [personalcancertoolkit/openmrs-module-healthybehaviors#44]
What did I do in the last 30 days?  Plot as a bar for that 30 day. reporting period.  
Consider the point being date reported (13-Jul)

**Comment by uladkasach** [comment]
Rather than reporting for individual months, as defined in this ticket, we are now reporting for the past 30 days. This gives many advantages, such as reducing confusion when reporting and enabling the user to report over the last 30 days at any time, without needing to recall last month's progress.

This has been implemented in the following commit.

**Comment by uladkasach** [comment]
![image](https://user-images.githubusercontent.com/10381896/28339046-ddab1b7e-6bd8-11e7-88e1-8ed95aca6e5f.png)
Note:
- User has not yet been locked from inputting data only after 30 days has passed (thus data within 30 day intervals appears in the above graph)
-Graph is still only a line graph. A bar graph may make the data even easier to "digest".

**Comment by uladkasach** [comment]
![image](https://user-images.githubusercontent.com/10381896/28422720-eaa56db6-6d36-11e7-8b92-fe24cec4f79b.png)
In this graph, 30 day intervals were enforced.

With the line graph, because it "estimates" the performance between two periods based on previous and future values, perhaps this is actually a better representation.
